name: 🔧 test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12", "3.13", "3.x"]

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: 💼 Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e . --group test

      - name: 🧪 Run Doctests and Coverage
        with:
          verbose: true
        run: pytest --cov --cov-branch --cov-report=xml --doctest-modules .

      - name: 📈 Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
